import { useState, useEffect } from 'react';
/**
 * BCA DASHBOARD ARCHITECTURE (Stage 3)
 * 
 * This application is a high-fidelity React frontend designed to visualize 
 * structural macroeconomic findings from a Business Cycle Accounting (BCA) model.
 * 
 * Key Design Principles:
 * 1. Data-Driven: Fetches a static JSON (latest_quarter.json) generated by the Python pipeline.
 * 2. Visual-First: Uses Glassmorphism and Recharts for premium analytics.
 * 3. AI Hypothesis Layer: Dynamically renders qualitative insights generated by Gemini.
 */
import { 
  Activity, BarChart3, BrainCircuit, TrendingUp, TrendingDown, 
  AlertTriangle, ActivitySquare
} from 'lucide-react';
import { 
  BarChart, Bar, ComposedChart, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  LineChart, Line, Legend
} from 'recharts';
import './App.css';

/**
 * Data Contract between Python pipeline (Stage 2) and React frontend (Stage 3).
 * If the pipeline schema changes, this interface must be updated.
 */
interface BCAData {
  quarter: string; // The end of the BCA sample
  macro_quarter: string; // The latest quarter available in FRED/BEA headline data
  macro_overview: {
    gdp_growth_qoq: number;
    gdp_growth_yoy: number;
    components: {
      consumption: { growth_qoq: number; contribution_to_gdp: number };
      investment: { growth_qoq: number; contribution_to_gdp: number };
      government: { growth_qoq: number; contribution_to_gdp: number };
      exports: { growth_qoq: number; contribution_to_gdp: number };
      imports: { growth_qoq: number; contribution_to_gdp: number };
    };
    historical_percentiles: {
      gdp: number; // Percentile rank in historical sample
      investment: number;
      consumption: number;
    };
  };
  time_series: {
    demand_contributions: Array<{ quarter: string; A_Consumption: number; B_Investment: number; C_Government: number; D_Exports: number; "Total GDP Growth": number }>;
    supply_contributions: Array<{ quarter: string; Goods: number; Services: number; Government: number }>;
  };
  wedge_decomposition: {
    current_levels: Record<string, { sd_from_mean: number; percentile: number; trend: string }>;
    f_statistics: Record<string, number>; // Output Fluctuation Explained by Wedge (BCKM Table 11 inverse-SSR over the eval window)
    cf_time_series: Array<{
      quarter: string;
      Data: number;
      Efficiency: number;
      Labor: number;
      Investment: number;
      Government: number;
    }>;
  };
  hypothesis_layer: {
    pattern_identification: string;
    candidate_mechanisms: Array<{
      wedge: string;
      mechanism: string;
      citations: string[];
      reasoning: string;
    }>;
    what_to_watch: Array<{
      mechanism: string;
      indicator: string;
    }>;
  };
}

function App() {
  const [data, setData] = useState<BCAData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Fetch the production static data export
    fetch('/data/latest_quarter.json')
      .then(res => res.json())
      .then(jsonData => {
        setData(jsonData);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load data:", err);
        setLoading(false);
      });
  }, []);

  if (loading || !data) {
    return <div className="app-container" style={{ alignItems: 'center', justifyContent: 'center' }}>
      <ActivitySquare className="brand-icon" size={48} />
      <h2 style={{ marginTop: '1rem' }}>Loading BCA Data...</h2>
    </div>;
  }

  // Format f-stats for the chart
  const fStatChartData = Object.entries(data.wedge_decomposition.f_statistics).map(([name, value]) => ({
    name: name.charAt(0).toUpperCase() + name.slice(1),
    value: value * 100 // convert to percentage
  }));

  const renderArrow = (value: number) => {
    return value >= 0 
      ? <TrendingUp size={28} color="var(--success)" style={{ marginLeft: '0.5rem' }} />
      : <TrendingDown size={28} color="var(--danger)" style={{ marginLeft: '0.5rem' }} />;
  };

  const annualizeRate = (val: number) => (Math.pow(1 + val, 4) - 1) * 100;


  return (
    <div className="app-container">
      {/* HEADER */}
      <header className="app-header">
        <div className="header-brand">
          <div className="brand-icon">
            <Activity size={24} />
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', minWidth: 0 }}>
            <h1 className="brand-title">Business Cycle Monitor</h1>
            <span className="brand-subtitle">US Quarterly Structural Snapshot</span>
          </div>
        </div>
        <div className="header-status">
          <div className="status-dot"></div>
          <span>Updated: {data.macro_quarter || data.quarter} (NIPA Release)</span>
        </div>
      </header>

      <main className="main-content">
        
        {/* SCREEN 1: MACRO OVERVIEW */}
        <section>
          <div className="section-header">
            <BarChart3 className="text-accent" size={24} color="var(--accent-primary)" />
            <h2 className="section-title">Macro Overview</h2>
            <div className="section-divider"></div>
          </div>
          
          <div className="grid-6">
            <div className="glass-panel kpi-card">
              <span className="kpi-label">GDP Growth</span>
              <div style={{ display: 'flex', alignItems: 'center' }}>
                <span className="kpi-value">{annualizeRate(data.macro_overview.gdp_growth_qoq).toFixed(1)}%</span>
                {renderArrow(data.macro_overview.gdp_growth_qoq)}
              </div>
            </div>
            <div className="glass-panel kpi-card">
              <span className="kpi-label">Consumption</span>
              <div style={{ display: 'flex', alignItems: 'center' }}>
                <span className="kpi-value">{annualizeRate(data.macro_overview.components.consumption.growth_qoq).toFixed(1)}%</span>
                {renderArrow(data.macro_overview.components.consumption.growth_qoq)}
              </div>
            </div>
            <div className="glass-panel kpi-card">
              <span className="kpi-label">Investment</span>
              <div style={{ display: 'flex', alignItems: 'center' }}>
                <span className="kpi-value">{annualizeRate(data.macro_overview.components.investment.growth_qoq).toFixed(1)}%</span>
                {renderArrow(data.macro_overview.components.investment.growth_qoq)}
              </div>
            </div>
            <div className="glass-panel kpi-card">
              <span className="kpi-label">Government</span>
              <div style={{ display: 'flex', alignItems: 'center' }}>
                <span className="kpi-value">{annualizeRate(data.macro_overview.components.government.growth_qoq).toFixed(1)}%</span>
                {renderArrow(data.macro_overview.components.government.growth_qoq)}
              </div>
            </div>
            <div className="glass-panel kpi-card">
              <span className="kpi-label">Exports</span>
              <div style={{ display: 'flex', alignItems: 'center' }}>
                <span className="kpi-value">{annualizeRate(data.macro_overview.components.exports.growth_qoq).toFixed(1)}%</span>
                {renderArrow(data.macro_overview.components.exports.growth_qoq)}
              </div>
            </div>
            <div className="glass-panel kpi-card">
              <span className="kpi-label">Imports</span>
              <div style={{ display: 'flex', alignItems: 'center' }}>
                <span className="kpi-value">{annualizeRate(data.macro_overview.components.imports.growth_qoq).toFixed(1)}%</span>
                {renderArrow(data.macro_overview.components.imports.growth_qoq)}
              </div>
            </div>
          </div>
          <div style={{ marginTop: '1rem', fontSize: '0.875rem', color: 'var(--text-muted)' }}>
            * Note: All macro overview figures represent QoQ annualized rates or contributions to GDP.
          </div>

          <div style={{ marginTop: '2rem' }}>
            <div className="glass-panel">
              <h3 style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>Demand Contributions to Growth</h3>
              <div className="chart-container">
                <ResponsiveContainer width="100%" height="100%">
                  <ComposedChart data={data.time_series.demand_contributions.slice(-8)} stackOffset="sign" margin={{ top: 5, right: 20, left: -20, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" vertical={false} />
                    <XAxis dataKey="quarter" stroke="var(--text-muted)" fontSize={10} tick={{ fontSize: 10 }} />
                    <YAxis stroke="var(--text-muted)" fontSize={10} tick={{ fontSize: 10 }} />
                    <Tooltip contentStyle={{ backgroundColor: 'var(--bg-surface)', borderColor: 'var(--border-color)' }} />
                    <Legend content={() => {
                      const items = [
                        { label: 'Consumption', color: '#3b82f6' },
                        { label: 'Investment', color: '#8b5cf6' },
                        { label: 'Government', color: '#10b981' },
                        { label: 'Net Exports', color: '#f59e0b' },
                        { label: 'Total GDP Growth', color: '#ffffff', isLine: true }
                      ];
                      return (
                        <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: '1.5rem', marginTop: '1rem', fontSize: '0.75rem' }}>
                          {items.map(item => (
                            <div key={item.label} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                              <div style={{ 
                                width: item.isLine ? '12px' : '8px', 
                                height: item.isLine ? '2px' : '8px', 
                                backgroundColor: item.color,
                                borderRadius: item.isLine ? '0' : '2px'
                              }}></div>
                              <span style={{ color: 'var(--text-muted)' }}>{item.label}</span>
                            </div>
                          ))}
                        </div>
                      );
                    }} />
                    <Bar dataKey="A_Consumption" name="Consumption" stackId="a" fill="#3b82f6" />
                    <Bar dataKey="B_Investment" name="Investment" stackId="a" fill="#8b5cf6" />
                    <Bar dataKey="C_Government" name="Government" stackId="a" fill="#10b981" />
                    <Bar dataKey="D_Exports" name="Net Exports" stackId="a" fill="#f59e0b" />
                    <Line type="monotone" dataKey="Total GDP Growth" stroke="#ffffff" strokeWidth={2} dot={{ r: 3, fill: '#ffffff' }} />
                  </ComposedChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>
        </section>

        {/* SCREEN 2: WEDGE DECOMPOSITION */}
        <section>
          <div className="section-header">
            <ActivitySquare className="text-accent" size={24} color="var(--accent-primary)" />
            <h2 className="section-title">Wedge Decomposition</h2>
            <div className="section-divider"></div>
          </div>
          <div style={{ color: 'var(--text-muted)', fontSize: '0.875rem', marginBottom: '1.5rem', lineHeight: 1.55 }}>
            <strong style={{ color: 'var(--text-secondary)' }}>Evaluation window:</strong> 2023Q1 → {data.quarter}. Both panels are anchored at 2023Q1. Structural wedges reported up to {data.quarter} due to auxiliary data release lags.
          </div>

          <div className="grid-2">
            <div className="glass-panel">
              <h3 style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>Share of Output Fluctuation Explained by Wedge</h3>
              <div className="chart-container">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={fStatChartData} layout="vertical" margin={{ top: 5, right: 30, left: 80, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" horizontal={true} vertical={false} />
                    <XAxis type="number" unit="%" stroke="var(--text-muted)" />
                    <YAxis dataKey="name" type="category" stroke="var(--text-muted)" />
                    <Tooltip cursor={{ fill: 'rgba(255,255,255,0.05)' }} contentStyle={{ backgroundColor: 'var(--bg-surface)', borderColor: 'var(--border-color)', borderRadius: '8px' }} />
                    <Bar dataKey="value" fill="var(--accent-primary)" radius={[0, 4, 4, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>

            <div className="glass-panel" style={{ display: 'flex', flexDirection: 'column', minWidth: 0 }}>
              <h3 style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>Output Components (2023Q1 = 100)</h3>
              
              <div style={{ flex: 1, minHeight: '250px', marginBottom: '1.5rem', minWidth: 0 }}>
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={data.wedge_decomposition.cf_time_series} margin={{ top: 5, right: 20, left: -20, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" vertical={false} />
                    <XAxis dataKey="quarter" stroke="var(--text-muted)" fontSize={10} tick={{ fontSize: 10 }} />
                    <YAxis stroke="var(--text-muted)" fontSize={10} domain={['auto', 'auto']} tick={{ fontSize: 10 }} />
                    <Tooltip contentStyle={{ backgroundColor: 'var(--bg-surface)', borderColor: 'var(--border-color)' }} />
                    <Legend />
                    <Line type="monotone" dataKey="Data" stroke="#ffffff" strokeWidth={3} dot={false} />
                    <Line type="monotone" dataKey="Efficiency" stroke="#3b82f6" strokeDasharray="5 5" strokeWidth={2} dot={false} />
                    <Line type="monotone" dataKey="Labor" stroke="#10b981" strokeDasharray="3 4 5 4" strokeWidth={2} dot={false} />
                    <Line type="monotone" dataKey="Investment" stroke="#8b5cf6" strokeDasharray="1 3" strokeWidth={2} dot={false} />
                    <Line type="monotone" dataKey="Government" stroke="#f59e0b" strokeDasharray="2 2" strokeWidth={2} dot={false} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>
          <div style={{ color: 'var(--text-muted)', fontSize: '0.875rem', marginTop: '1.5rem', lineHeight: 1.55 }}>
            <strong style={{ color: 'var(--text-secondary)' }}>Caveat:</strong> the share metric (left) uses inverse-SSR — when observed output (white line, right) is near-flat, it mechanically favors whichever counterfactual stayed closest to flat, often the wedge that did the <em>least</em>. In that regime the right panel is more informative: large offsetting swings describe what each wedge would have done acting alone, even when its share is small.
          </div>
        </section>

        {/* WEDGE EXPLANATION BOX */}
        <section>
          <div className="glass-panel" style={{ background: 'rgba(59, 130, 246, 0.05)', borderLeft: '4px solid var(--accent-primary)' }}>
            <h3 style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <ActivitySquare size={20} color="var(--accent-primary)" /> What do these wedges represent?
            </h3>
            <div className="grid-2" style={{ gap: '1rem' }}>
              <div>
                <strong style={{ color: 'white' }}>Efficiency Wedge:</strong> Acts like a technology parameter. It captures anything that lowers aggregate productivity (e.g., input financing frictions, resource misallocation, or trade disruptions).
              </div>
              <div>
                <strong style={{ color: 'white' }}>Labor Wedge:</strong> Acts like a tax on labor income. It represents anything that drives a wedge between the marginal rate of substitution and the marginal product of labor (e.g., search frictions, sticky wages, labor taxes).
              </div>
              <div>
                <strong style={{ color: 'white' }}>Investment Wedge:</strong> Acts like a tax on investment. It captures anything that makes it harder or more expensive to turn today's resources into tomorrow's capital (distortions to the intertemporal Euler equation), such as firm financing frictions, liquidity constraints, or uncertainty shocks.
              </div>
              <div>
                <strong style={{ color: 'white' }}>Government Wedge:</strong> Represents output that is absorbed outside of domestic private consumption and investment. It is measured directly from the data as the sum of government consumption and net exports.
              </div>
            </div>
          </div>
        </section>

        {/* SCREEN 3: HYPOTHESIS LAYER */}
        {data.hypothesis_layer && data.hypothesis_layer.pattern_identification && (
          <section>
            <div className="section-header">
              <BrainCircuit className="text-accent" size={24} color="var(--accent-secondary)" />
              <h2 className="section-title" style={{ color: 'var(--accent-secondary)' }}>Hypothesis Layer</h2>
              <div className="section-divider"></div>
            </div>

            <div className="glass-panel hypothesis-card">
              <div className="hypothesis-header">
                <Activity size={20} />
                <h3 style={{ margin: 0 }}>Pattern Identification</h3>
              </div>
              <p className="hypothesis-text">
                {data.hypothesis_layer.pattern_identification}
              </p>
            </div>

            <div className="grid-2" style={{ marginTop: '1.5rem' }}>
              <div className="glass-panel">
                <h3 style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>Candidate Mechanisms</h3>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
                  {data.hypothesis_layer.candidate_mechanisms?.map((mech, idx) => (
                    <div key={idx} style={{ paddingBottom: '1.5rem', borderBottom: idx !== data.hypothesis_layer.candidate_mechanisms.length - 1 ? '1px solid var(--border-color)' : 'none' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                        <span className="badge badge-purple">{mech.wedge} Wedge</span>
                        <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{mech.citations?.join(', ')}</span>
                      </div>
                      <h4 style={{ color: 'white' }}>{mech.mechanism}</h4>
                      <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginTop: '0.5rem' }}>{mech.reasoning}</p>
                    </div>
                  ))}
                </div>
              </div>

              <div className="glass-panel">
                <h3 style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>What to Watch</h3>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                  {data.hypothesis_layer.what_to_watch?.map((watch, idx) => (
                    <div key={idx} style={{ padding: '1rem', background: 'rgba(255,255,255,0.03)', borderRadius: 'var(--radius-md)' }}>
                      <h5 style={{ color: 'white', marginBottom: '0.25rem' }}>{watch.mechanism}</h5>
                      <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>{watch.indicator}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <div className="ai-warning">
              <AlertTriangle size={20} />
              <span><strong>Hypotheses generated by AI — not structural findings.</strong> Treat as a starting point for analysis, not a conclusion. Based on Gemini 2.5 Flash.</span>
            </div>
          </section>
        )}

      </main>
    </div>
  );
}

export default App;
