#!/usr/bin/env python3
"""Generate macro-event entries for one or more quarters.

Uses Gemini 2.5 Flash with Google Search grounding to produce a structured,
factual event log scoped to a single quarter at a time. Idempotent: scans
``data/events.md`` and skips quarters already present unless ``--force``.

Usage:
    GEMINI_API_KEY=... python scripts/generate_events.py 2023Q1
    GEMINI_API_KEY=... python scripts/generate_events.py 2023Q1 2023Q2 --force
"""
import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_EVENTS_PATH = REPO_ROOT / "data" / "events.md"

QUARTER_RANGES = {
    "Q1": ("01-01", "03-31"),
    "Q2": ("04-01", "06-30"),
    "Q3": ("07-01", "09-30"),
    "Q4": ("10-01", "12-31"),
}


def quarter_to_dates(quarter: str) -> tuple[str, str]:
    m = re.match(r"^(\d{4})Q([1-4])$", quarter)
    if not m:
        raise ValueError(f"Bad quarter format: {quarter!r} (expected e.g. '2023Q1')")
    year = m.group(1)
    start_md, end_md = QUARTER_RANGES[f"Q{m.group(2)}"]
    return f"{year}-{start_md}", f"{year}-{end_md}"


def existing_quarters(events_path: Path) -> set[str]:
    if not events_path.exists():
        return set()
    text = events_path.read_text()
    return set(re.findall(r"^## (\d{4}Q[1-4])\s*$", text, flags=re.MULTILINE))


def build_prompt(quarter: str) -> str:
    start_date, end_date = quarter_to_dates(quarter)
    return f"""You are a macroeconomic events archivist. Using Google Search, compile a tight, factual list of US-macro-relevant events that occurred during {quarter} ({start_date} to {end_date}).

Output rules:
- Markdown bullets only. Begin with `## {quarter}` as the header. No preamble, no closing remarks.
- Format: `- YYYY-MM-DD — [BUCKET] One-line factual description.` (YYYY-MM is acceptable if the exact day is uncertain; omit the event if you cannot date it to within a week.)
- BUCKET ∈ {{Monetary, Fiscal, Regulatory, Tech, Geopolitical}}.
- At most 3 entries per bucket. Omit buckets with no qualifying events. Quality over coverage.
- US-relevant only. Foreign events qualify only with documented, direct spillover to US monetary / fiscal / trade / financial conditions (e.g., OPEC quota change, China stimulus, major foreign tariff retaliation).
- Factual events only — actions taken, decisions made, laws passed, data releases, policy announcements. NO market commentary, NO forecasts, NO "this signals" framing.
- Prefer high-confidence, well-documented events. If uncertain, omit.
"""


def generate_quarter_events(quarter: str, gemini_key: str) -> str:
    from google import genai
    from google.genai import types

    client = genai.Client(api_key=gemini_key)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=build_prompt(quarter),
        config=types.GenerateContentConfig(
            tools=[types.Tool(google_search=types.GoogleSearch())],
        ),
    )
    text = (response.text or "").strip()
    if not text.startswith(f"## {quarter}"):
        text = f"## {quarter}\n\n" + text
    return text


def append_quarter(events_path: Path, quarter_md: str) -> None:
    events_path.parent.mkdir(parents=True, exist_ok=True)
    if events_path.exists():
        existing = events_path.read_text().rstrip()
        events_path.write_text(existing + "\n\n" + quarter_md + "\n")
    else:
        header = (
            "# US Macro Events Log\n\n"
            "Automated per-quarter event log generated by "
            "`scripts/generate_events.py`. Each quarter is generated once "
            "with Google Search grounding and frozen.\n"
        )
        events_path.write_text(header + "\n" + quarter_md + "\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("quarters", nargs="+", help="e.g. 2023Q1 2023Q2")
    parser.add_argument("--force", action="store_true", help="Regenerate even if already present")
    parser.add_argument("--out", default=str(DEFAULT_EVENTS_PATH))
    args = parser.parse_args()

    gemini_key = os.environ.get("GEMINI_API_KEY")
    if not gemini_key:
        print("Error: GEMINI_API_KEY not set", file=sys.stderr)
        return 1

    out_path = Path(args.out)
    existing = set() if args.force else existing_quarters(out_path)

    for quarter in args.quarters:
        try:
            quarter_to_dates(quarter)
        except ValueError as e:
            print(f"  {quarter}: {e}", file=sys.stderr)
            continue
        if quarter in existing:
            print(f"  {quarter}: already present, skipping (use --force to regenerate)")
            continue
        print(f"  {quarter}: generating...")
        try:
            md = generate_quarter_events(quarter, gemini_key)
        except Exception as e:
            print(f"  {quarter}: FAILED ({type(e).__name__}: {e})", file=sys.stderr)
            continue
        append_quarter(out_path, md)
        print(f"  {quarter}: wrote {len(md)} chars to {out_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
